######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 17 22:11:55 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += puzzlemodel.h puzzleview.h puzzlewindow.h title.h
FORMS += puzzlewindow.ui
SOURCES += main.cpp puzzlemodel.cpp puzzleview.cpp puzzlewindow.cpp title.cpp
